# path: /v1/applications/{applicationId}/export_effects
get:
  operationId: exportEffects
  summary: Export triggered effects
  description: >
    <div class="redoc-warning small">Management API endpoints are <b>not</b>
    meant to be used in real-time integrations that directly serve your end
    users. Rate limit: 3 requests per second.</div>


    Download a CSV file containing the triggered effects that match the given
    attributes.


    **Tip:** If the exported CSV file is too large to view, you can [split it
    into multiple
    files](https://www.makeuseof.com/tag/how-to-split-a-huge-csv-excel-workbook-into-seperate-files/).


    The generated file can contain the following columns:


    - `applicationid`: The ID of the Application.

    - `campaignid`: The ID of the campaign.

    - `couponid`: The ID of the coupon, when applicable to the effect.

    - `created`: The timestamp of the effect.

    - `event_type`: The name of the event. See the
    [docs](https://docs.talon.one/docs/dev/concepts/entities/events).

    - `eventid`: The internal ID of the effect.

    - `name`: The effect name. See the
    [docs](https://docs.talon.one/docs/dev/integration-api/api-effects).

    - `profileintegrationid`: The ID of the customer profile, when applicable.

    - `props`: The
    [properties](https://docs.talon.one/docs/dev/integration-api/api-effects) of
    the effect.

    - `ruleindex`: The index of the rule.

    - `rulesetid`: The ID of the rule set.

    - `sessionid`: The internal ID of the session that triggered the effect.

    - `profileid`: The internal ID of the customer profile.

    - `sessionintegrationid`: The integration ID of the session.

    - `total_revenue`: The total revenue.

    - `store_integration_id`: The integration ID of the store. You choose this
    ID when you create a store.
  tags:
    - Analytics
  parameters:
    - name: applicationId
      in: path
      required: true
      description: >-
        The ID of the Application. It is displayed in your Talon.One deployment
        URL.
      example: 42
      schema:
        type: integer
    - name: campaignId
      in: query
      description: Filter results by campaign ID.
      example: 49
      schema:
        type: number
    - name: createdBefore
      in: query
      description: >-
        Filter results comparing the parameter value, expected to be an RFC3339
        timestamp string. You can use any time zone setting. Talon.One will
        convert to UTC internally.
      required: false
      example: '2024-05-29T15:04:05+07:00'
      schema:
        type: string
        format: date-time
    - name: createdAfter
      in: query
      description: >-
        Filter results comparing the parameter value, expected to be an RFC3339
        timestamp string. You can use any time zone setting. Talon.One will
        convert to UTC internally.
      required: false
      example: '2024-05-29T15:04:05+07:00'
      schema:
        type: string
        format: date-time
    - name: dateFormat
      in: query
      description: Determines the format of dates in the export document.
      example: excel
      required: false
      schema:
        type: string
        enum:
          - excel
          - ISO8601
  responses:
    '200':
      description: OK
      content:
        application/csv:
          schema:
            type: string
            format: csv
          examples:
            response:
              value: >
                created,name,applicationid,campaignid,rulesetid,ruleindex,sessionintegrationid,profileintegrationid,sessionid,profileid,eventid,event_type,total_revenue,props,couponid,store_id,store_integration_id

                2021-06-02T21:14:16Z,rejectCoupon,270,0,0,0,newsession1,,9168,0,95797,talon_session_created,265.00,"{""value"":
                ""XMAS20"", ""rejectionReason"":
                ""CouponNotFound""}",,115,STORE-001

                2021-09-01T13:04:04Z,setDiscountPerItem,270,3882,13599,0,test_flattening_2,integid_4,9707,4800,98806,talon_session_updated,405.00,"{""name"":
                ""10% off per item#1"", ""value"": 11.0, ""position"":
                1}",,116,STORE-002
