# path: /v1/applications/{applicationId}/sessions/{sessionId}
get:
  operationId: getApplicationSession
  summary: Get Application session
  description: >
    <div class="redoc-warning small">Management API endpoints are <b>not</b>
    meant to be used in real-time integrations that directly serve your end
    users. Rate limit: 3 requests per second.</div>


    Get the details of the given session.

    You can list the sessions with the [List Application
    sessions](https://docs.talon.one/management-api#tag/Customer-data/operation/getApplicationSessions)
    endpoint.
  tags:
    - Customer data
  parameters:
    - name: applicationId
      in: path
      required: true
      description: >-
        The ID of the Application. It is displayed in your Talon.One deployment
        URL.
      example: 42
      schema:
        type: integer
    - name: sessionId
      in: path
      description: >
        The **internal** ID of the session. You can get the ID with the [List
        Application
        sessions](https://docs.talon.one/management-api#tag/Customer-data/operation/getApplicationSessions)
        endpoint.
      example: 2533
      required: true
      schema:
        type: integer
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            allOf:
              - type: object
                required:
                  - id
                  - created
                properties:
                  id:
                    type: integer
                    description: The internal ID of this entity.
                    example: 6
                  created:
                    type: string
                    format: date-time
                    description: The time this entity was created.
                    example: '2020-06-10T09:05:27.993483Z'
              - type: object
                required:
                  - integrationId
                  - created
                properties:
                  integrationId:
                    type: string
                    format: string
                    example: URNGV8294NV
                    maxLength: 1000
                    description: The integration ID set by your integration layer.
                  created:
                    type: string
                    format: date-time
                    description: The time this entity was created.
                    example: '2020-02-07T08:15:22Z'
              - type: object
                properties:
                  storeIntegrationId:
                    type: string
                    minLength: 1
                    maxLength: 1000
                    description: >-
                      The integration ID of the store. You choose this ID when
                      you create a store.
                    example: STORE-001
              - type: object
                required:
                  - applicationId
                properties:
                  applicationId:
                    type: integer
                    description: The ID of the Application that owns this entity.
                    example: 322
              - type: object
                properties:
                  profileId:
                    type: integer
                    description: >-
                      The globally unique Talon.One ID of the customer that
                      created this entity.
                    example: 138
              - type: object
                properties:
                  profileintegrationid:
                    type: string
                    maxLength: 1000
                    description: Integration ID of the customer for the session.
                    example: 382370BKDB946
                  coupon:
                    type: string
                    description: Any coupon code entered.
                    example: BKDB946
                  referral:
                    type: string
                    description: Any referral code entered.
                    example: BKDB946
                  state:
                    type: string
                    enum:
                      - open
                      - closed
                      - partially_returned
                      - cancelled
                    description: >
                      Indicates the current state of the session. Sessions can
                      be created as `open` or `closed`. The state transitions
                      are:


                      1. `open` → `closed`

                      2. `open` → `cancelled`

                      3. `closed` → `cancelled` or `partially_returned`

                      4. `partially_returned` → `cancelled`


                      For more information, see [Customer session
                      states](https://docs.talon.one/docs/dev/concepts/entities/customer-sessions).
                    example: closed
                  cartItems:
                    type: array
                    description: Serialized JSON representation.
                    items:
                      type: object
                      required:
                        - sku
                        - quantity
                      properties:
                        name:
                          title: Name of item
                          type: string
                          description: Name of item.
                          example: Air Glide
                        sku:
                          title: SKU of item
                          type: string
                          description: Stock keeping unit of item.
                          minLength: 1
                          example: SKU1241028
                        quantity:
                          title: Quantity of item
                          type: integer
                          description: >
                            Number of units of this item. Due to [cart item
                            flattening](https://docs.talon.one/docs/product/rules/understanding-cart-item-flattening),

                            if you provide a quantity greater than 1, the item
                            will be split in as many items as the provided
                            quantity.

                            This will impact the number of **per-item** effects
                            triggered from your campaigns.
                          minimum: 1
                          example: 1
                        returnedQuantity:
                          title: Returned quantity of item
                          type: integer
                          description: >-
                            Number of returned items, calculated internally
                            based on returns of this item.
                          example: 1
                        remainingQuantity:
                          title: Remaining quantity of item
                          type: integer
                          description: >-
                            Remaining quantity of the item, calculated
                            internally based on returns of this item.
                          example: 1
                        price:
                          title: Price of item
                          type: number
                          description: >
                            Price of the item in the currency defined by your
                            Application. This field is required if this item is
                            not part of a
                            [catalog](https://docs.talon.one/docs/product/account/dev-tools/managing-cart-item-catalogs).
                            If it is part of a catalog, setting a price here
                            overrides the price from the catalog.
                          example: 99.99
                        category:
                          title: Item category
                          type: string
                          description: Type, group or model of the item.
                          example: shoes
                        product:
                          title: Item product
                          type: object
                          description: >-
                            The specific properties of the product this item
                            belongs to, if available.
                          required:
                            - name
                          properties:
                            name:
                              type: string
                              description: The product the item belongs to.
                              example: sample_product
                        weight:
                          title: Weight of item
                          type: number
                          description: Weight of item in grams.
                          example: 1130
                        height:
                          title: Height of item
                          type: number
                          description: Height of item in mm.
                        width:
                          title: Width of item
                          type: number
                          description: Width of item in mm.
                        length:
                          title: Length of item
                          type: number
                          description: Length of item in mm.
                        position:
                          title: Position of Cart Item
                          type: number
                          description: >-
                            Position of the Cart Item in the Cart (calculated
                            internally).
                        attributes:
                          title: Item attributes
                          type: object
                          description: >
                            Use this property to set a value for the attributes
                            of your choice.
                            [Attributes](https://docs.talon.one/docs/dev/concepts/attributes)
                            represent any information to attach to this cart
                            item.


                            Custom _cart item_ attributes must be created in the
                            Campaign Manager before you set them with this
                            property.


                            **Note:** Any previously defined attributes that you
                            do not include in the array will be removed.
                          example:
                            image: 11.jpeg
                            material: leather
                        additionalCosts:
                          type: object
                          description: >
                            Use this property to set a value for the additional
                            costs of this item, such as a shipping cost. They
                            must be created in the Campaign Manager

                            before you set them with this property. See
                            [Managing additional
                            costs](https://docs.talon.one/docs/product/account/dev-tools/managing-additional-costs).
                          additionalProperties:
                            type: object
                            required:
                              - price
                            properties:
                              price:
                                title: Price of additional cost
                                type: number
                                example: 4.5
                          example:
                            shipping:
                              price: 9
                        catalogItemID:
                          title: The catalog item ID
                          type: integer
                          description: The catalog item ID.
                        selectedPriceType:
                          title: Price Type
                          type: string
                          description: >-
                            The selected price type for this cart item (e.g. the
                            price for members only).
                          example: member
                        adjustmentReferenceId:
                          title: Price Adjustment ID
                          type: string
                          format: uuid
                          description: >-
                            The reference ID of the selected price adjustment
                            for this cart item. Only returned if the selected
                            price resulted from a price adjustment.
                          example: 68851723-e6fa-488f-ace9-112581e6c19b
                        adjustmentEffectiveFrom:
                          title: Price Adjustment Start Date
                          type: string
                          format: date-time
                          description: >-
                            The date and time from which the price adjustment is
                            effective. Only returned if the selected price
                            resulted from a price adjustment that contains this
                            field.
                          example: '2021-09-12T10:12:42Z'
                        adjustmentEffectiveUntil:
                          title: Price Adjustment Expiry Date
                          type: string
                          format: date-time
                          description: >-
                            The date and time until which the price adjustment
                            is effective. Only returned if the selected price
                            resulted from a price adjustment that contains this
                            field.
                          example: '2021-09-12T10:12:42Z'
                        prices:
                          type: object
                          description: >
                            A map of keys and values representing the price
                            types and related price adjustment details for this
                            cart item.

                            The keys correspond to the `priceType` names.
                          additionalProperties:
                            type: object
                            properties:
                              price:
                                type: number
                                format: float
                                description: The value of this price type.
                                example: 90
                              adjustmentContextId:
                                type: string
                                description: >-
                                  The context identifier of the selected price
                                  adjustment.
                                example: summer25
                              adjustmentReferenceId:
                                type: string
                                format: uuid
                                description: >-
                                  The reference identifier of the selected price
                                  adjustment for this SKU.
                                example: 68851723-e6fa-488f-ace9-112581e6c19b
                              adjustmentEffectiveFrom:
                                type: string
                                format: date-time
                                description: >-
                                  The date and time from which the price
                                  adjustment is effective.
                                example: '2025-05-25T00:00:00Z'
                              adjustmentEffectiveUntil:
                                type: string
                                format: date-time
                                description: >-
                                  The date and time until which the price
                                  adjustment is effective.
                                example: '2025-05-30T00:00:00Z'
                          example:
                            member:
                              price: 90
                              adjustmentReferenceId: 68851723-e6fa-488f-ace9-112581e6c19b
                              effectiveFrom: '2025-05-25T00:00:00Z'
                              effectiveUntil: '2025-05-30T00:00:00Z'
                            base:
                              price: 100
                  discounts:
                    type: object
                    description: >
                      **API V1 only.** A map of labeled discount values, in the
                      same currency as the session.


                      If you are using the V2 endpoints, refer to the
                      `totalDiscounts` property instead.
                    additionalProperties:
                      type: number
                  totalDiscounts:
                    type: number
                    description: >
                      The total sum of the discounts applied to this session.


                      **Note:** If more than one session is returned, this value
                      is displayed as `0`.
                    example: 100
                  total:
                    type: number
                    description: The total sum of the session before any discounts applied.
                    example: 200
                  attributes:
                    type: object
                    description: Arbitrary properties associated with this item.
                required:
                  - coupon
                  - referral
                  - state
                  - cartItems
                  - discounts
                  - total
                  - totalDiscounts
