# path: /v1/applications/{applicationId}/campaigns/{campaignId}/import_coupons
post:
  operationId: importCoupons
  summary: Import coupons
  description: >
    <div class="redoc-warning small">Management API endpoints are <b>not</b>
    meant to be used in real-time integrations that directly serve your end
    users. Rate limit: 3 requests per second.</div>


    Upload a CSV file containing the coupons that should be created. The file
    should be sent as multipart data.


    The CSV file contains the following columns:


    - `value` (required): The coupon code.

    - `expirydate`: The end date in RFC3339 of the code redemption period.

    - `startdate`: The start date in RFC3339 of the code redemption period.

    - `recipientintegrationid`: The integration ID of the recipient of the
    coupon.
      Only the customer with this integration ID can redeem this code. Available only for personal codes.
    - `limitval`: The maximum number of redemptions of this code. For unlimited
    redemptions, use `0`. Defaults to `1` when not provided.

    - `discountlimit`: The total discount value that the code can give. This is
    typically used to represent a gift card value.

    - `attributes`: A JSON object describing _custom_ coupon attribute names and
    their values, enclosed with double quotation marks.

      For example, if you created a [custom attribute](https://docs.talon.one/docs/dev/concepts/attributes#custom-attributes)
      called `category` associated with the coupon entity, the object in the CSV file, when opened in a text editor, must be: `"{"category": "10_off"}"`.

    You can use the time zone of your choice. It is converted to UTC internally
    by Talon.One.


    **Note:** We recommend limiting your file size to 500MB.


    **Example:**


    ```text

    "value","expirydate","startdate","recipientintegrationid","limitval","attributes","discountlimit"

    COUP1,2018-07-01T04:00:00Z,2018-05-01T04:00:00Z,cust123,1,"{""Category"":
    ""10_off""}",2.4

    ```


    Once imported, you can find the `batchId` in the Campaign Manager or by

    using [List coupons](#tag/Coupons/operation/getCouponsWithoutTotalCount).
  tags:
    - Coupons
  requestBody:
    required: true
    content:
      multipart/form-data:
        schema:
          type: object
          properties:
            upFile:
              description: The file containing the data that is being imported.
              type: string
              format: csv
  parameters:
    - name: applicationId
      in: path
      required: true
      description: >-
        The ID of the Application. It is displayed in your Talon.One deployment
        URL.
      example: 42
      schema:
        type: integer
    - name: campaignId
      in: path
      description: >-
        The ID of the campaign. It is displayed in your Talon.One deployment
        URL.
      example: 18
      required: true
      schema:
        type: integer
    - name: skipDuplicates
      in: query
      required: false
      description: >
        An indicator of whether to skip duplicate coupon values instead of
        causing an error.

        Duplicate values are ignored when `skipDuplicates=true`.
      example: false
      schema:
        type: boolean
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            allOf:
              - type: object
                required:
                  - id
                  - created
                properties:
                  id:
                    type: integer
                    description: The internal ID of this entity.
                    example: 6
                  created:
                    type: string
                    format: date-time
                    description: The time this entity was created.
                    example: '2020-06-10T09:05:27.993483Z'
              - type: object
                required:
                  - accountId
                properties:
                  accountId:
                    type: integer
                    description: The ID of the account that owns this entity.
                    example: 3886
              - type: object
                required:
                  - userId
                properties:
                  userId:
                    type: integer
                    description: The ID of the user associated with this entity.
                    example: 388
              - type: object
                required:
                  - amount
                  - entity
                properties:
                  entity:
                    type: string
                    example: AttributeAllowedList
                    description: |
                      The name of the entity that was imported.
                  amount:
                    type: integer
                    minimum: 0
                    example: 10
                    description: The number of values that were imported.
