# path: /v1/applications/{applicationId}/profile/{integrationId}/friends
get:
  operationId: getApplicationCustomerFriends
  summary: List friends referred by customer profile
  description: >
    <div class="redoc-warning small">Management API endpoints are <b>not</b>
    meant to be used in real-time integrations that directly serve your end
    users. Rate limit: 3 requests per second.</div>


    List the friends referred by the specified customer profile in this
    Application.
  tags:
    - Referrals
  parameters:
    - name: pageSize
      in: query
      required: false
      description: The number of items in the response.
      example: 1000
      schema:
        type: integer
        minimum: 1
        maximum: 1000
        default: 1000
    - name: skip
      in: query
      required: false
      description: The number of items to skip when paging through large result sets.
      example: 100
      schema:
        type: integer
    - name: sort
      in: query
      required: false
      description: >
        The field by which results should be sorted. By default, results are
        sorted in ascending order. To sort them in descending order, prefix the
        field name with `-`.


        **Note:** You may not be able to use all fields for sorting. This is due
        to performance limitations.
      example: name
      schema:
        type: string
    - name: applicationId
      in: path
      required: true
      description: >-
        The ID of the Application. It is displayed in your Talon.One deployment
        URL.
      example: 42
      schema:
        type: integer
    - name: withTotalResultSize
      in: query
      description: >
        When this flag is set, the result includes the total size of the result,
        across all pages. This might decrease performance on large data sets.


        - When `true`: `hasMore` is true when there is a next page.
        `totalResultSize` is always zero.

        - When `false`: `hasMore` is always false. `totalResultSize` contains
        the total number of results for this query.
      example: false
      schema:
        type: boolean
    - name: integrationId
      in: path
      required: true
      description: The Integration ID of the Advocate's Profile.
      example: advocate1
      schema:
        type: string
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object
            required:
              - data
            properties:
              hasMore:
                type: boolean
              totalResultSize:
                type: integer
                example: 1
              data:
                type: array
                items:
                  allOf:
                    - type: object
                      required:
                        - applicationId
                      properties:
                        applicationId:
                          type: integer
                          description: The ID of the Application that owns this entity.
                          example: 322
                    - type: object
                      required:
                        - sessionId
                        - advocateIntegrationId
                        - friendIntegrationId
                        - code
                        - created
                      properties:
                        sessionId:
                          type: string
                          description: >-
                            Integration ID of the session in which the customer
                            redeemed the referral.
                        advocateIntegrationId:
                          type: string
                          maxLength: 1000
                          title: Advocate's Profile ID
                          description: Integration ID of the Advocate's Profile.
                        friendIntegrationId:
                          type: string
                          maxLength: 1000
                          title: Friend's Profile ID
                          description: Integration ID of the Friend's Profile.
                        code:
                          type: string
                          description: Advocate's referral code.
                        created:
                          type: string
                          format: date-time
                          description: >-
                            Timestamp of the moment the customer redeemed the
                            referral.
