# path: /v1/applications/{applicationId}/stores
get:
  operationId: listStores
  summary: List stores
  description: >-
    <div class="redoc-warning small">Management API endpoints are <b>not</b>
    meant to be used in real-time integrations that directly serve your end
    users. Rate limit: 3 requests per second.</div>


    List all stores for a specific Application.
  tags:
    - Stores
  parameters:
    - name: applicationId
      in: path
      required: true
      description: >-
        The ID of the Application. It is displayed in your Talon.One deployment
        URL.
      example: 42
      schema:
        type: integer
    - name: pageSize
      in: query
      required: false
      description: The number of items in the response.
      example: 1000
      schema:
        type: integer
        minimum: 1
        maximum: 1000
        default: 1000
    - name: skip
      in: query
      required: false
      description: The number of items to skip when paging through large result sets.
      example: 100
      schema:
        type: integer
    - name: sort
      in: query
      required: false
      description: >
        The field by which results should be sorted. By default, results are
        sorted in ascending order. To sort them in descending order, prefix the
        field name with `-`.


        **Note:** You may not be able to use all fields for sorting. This is due
        to performance limitations.
      example: name
      schema:
        type: string
    - name: withTotalResultSize
      in: query
      description: >
        When this flag is set, the result includes the total size of the result,
        across all pages. This might decrease performance on large data sets.


        - When `true`: `hasMore` is true when there is a next page.
        `totalResultSize` is always zero.

        - When `false`: `hasMore` is always false. `totalResultSize` contains
        the total number of results for this query.
      example: false
      schema:
        type: boolean
    - name: campaignId
      in: query
      description: Filter results by campaign ID.
      example: 49
      schema:
        type: number
    - name: name
      description: The name of the store.
      example: store1
      required: false
      in: query
      schema:
        type: string
    - name: integrationId
      description: The integration ID of the store.
      example: storeId1
      required: false
      in: query
      schema:
        type: string
    - name: query
      description: Filter results by `name` or `integrationId`.
      example: name
      required: false
      in: query
      schema:
        type: string
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object
            required:
              - data
            properties:
              hasMore:
                type: boolean
              totalResultSize:
                type: integer
                example: 1
              data:
                type: array
                items:
                  allOf:
                    - type: object
                      required:
                        - id
                        - created
                      properties:
                        id:
                          type: integer
                          description: The internal ID of this entity.
                          example: 6
                        created:
                          type: string
                          format: date-time
                          description: The time this entity was created.
                          example: '2020-06-10T09:05:27.993483Z'
                    - allOf:
                        - type: object
                          required:
                            - name
                            - description
                          properties:
                            name:
                              type: string
                              description: The name of the store.
                              example: South US store
                              minLength: 1
                              maxLength: 200
                            description:
                              type: string
                              description: The description of the store.
                              example: >-
                                This is the description of the store in south
                                US.
                            attributes:
                              type: object
                              description: The attributes of the store.
                              example:
                                country: USA
                                code: 1234
                        - type: object
                          required:
                            - integrationId
                          properties:
                            integrationId:
                              type: string
                              format: string
                              example: STORE-001
                              maxLength: 1000
                              minLength: 1
                              description: >
                                The integration ID of the store. You choose this
                                ID when you create a store.


                                **Note**: You cannot edit the `integrationId`
                                after the store has been created.
                    - type: object
                      required:
                        - updated
                        - applicationId
                        - integrationId
                        - created
                      properties:
                        created:
                          type: string
                          format: date-time
                          description: The time this entity was created.
                          example: '2020-02-07T08:15:22Z'
                        applicationId:
                          type: integer
                          description: The ID of the Application that owns this entity.
                          example: 322
                        updated:
                          type: string
                          format: date-time
                          description: Timestamp of the most recent update on this entity.
                          example: '2021-09-23T10:12:42Z'
                        linkedCampaignIds:
                          type: array
                          description: >-
                            A list of IDs of the campaigns that are linked with
                            current store.
                          items:
                            type: integer
                          example:
                            - 4
                            - 6
                            - 8
post:
  operationId: createStore
  summary: Create store
  description: >-
    <div class="redoc-warning small">Management API endpoints are <b>not</b>
    meant to be used in real-time integrations that directly serve your end
    users. Rate limit: 3 requests per second.</div>


    Create a new store in a specific Application.
  tags:
    - Stores
  parameters:
    - name: applicationId
      in: path
      required: true
      description: >-
        The ID of the Application. It is displayed in your Talon.One deployment
        URL.
      example: 42
      schema:
        type: integer
  requestBody:
    content:
      application/json:
        schema:
          allOf:
            - type: object
              required:
                - name
                - description
              properties:
                name:
                  type: string
                  description: The name of the store.
                  example: South US store
                  minLength: 1
                  maxLength: 200
                description:
                  type: string
                  description: The description of the store.
                  example: This is the description of the store in south US.
                attributes:
                  type: object
                  description: The attributes of the store.
                  example:
                    country: USA
                    code: 1234
            - type: object
              required:
                - integrationId
              properties:
                integrationId:
                  type: string
                  format: string
                  example: STORE-001
                  maxLength: 1000
                  minLength: 1
                  description: >
                    The integration ID of the store. You choose this ID when you
                    create a store.


                    **Note**: You cannot edit the `integrationId` after the
                    store has been created.
    description: body
    required: true
  responses:
    '201':
      description: Created
      content:
        application/json:
          schema:
            allOf:
              - type: object
                required:
                  - id
                  - created
                properties:
                  id:
                    type: integer
                    description: The internal ID of this entity.
                    example: 6
                  created:
                    type: string
                    format: date-time
                    description: The time this entity was created.
                    example: '2020-06-10T09:05:27.993483Z'
              - allOf:
                  - type: object
                    required:
                      - name
                      - description
                    properties:
                      name:
                        type: string
                        description: The name of the store.
                        example: South US store
                        minLength: 1
                        maxLength: 200
                      description:
                        type: string
                        description: The description of the store.
                        example: This is the description of the store in south US.
                      attributes:
                        type: object
                        description: The attributes of the store.
                        example:
                          country: USA
                          code: 1234
                  - type: object
                    required:
                      - integrationId
                    properties:
                      integrationId:
                        type: string
                        format: string
                        example: STORE-001
                        maxLength: 1000
                        minLength: 1
                        description: >
                          The integration ID of the store. You choose this ID
                          when you create a store.


                          **Note**: You cannot edit the `integrationId` after
                          the store has been created.
              - type: object
                required:
                  - updated
                  - applicationId
                  - integrationId
                  - created
                properties:
                  created:
                    type: string
                    format: date-time
                    description: The time this entity was created.
                    example: '2020-02-07T08:15:22Z'
                  applicationId:
                    type: integer
                    description: The ID of the Application that owns this entity.
                    example: 322
                  updated:
                    type: string
                    format: date-time
                    description: Timestamp of the most recent update on this entity.
                    example: '2021-09-23T10:12:42Z'
                  linkedCampaignIds:
                    type: array
                    description: >-
                      A list of IDs of the campaigns that are linked with
                      current store.
                    items:
                      type: integer
                    example:
                      - 4
                      - 6
                      - 8
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
                description: A message describing the error.
              errors:
                type: array
                description: >-
                  An array of individual problems encountered during the
                  request.
                items:
                  type: object
                  required:
                    - source
                    - title
                  properties:
                    title:
                      type: string
                      description: Short description of the problem.
                    details:
                      type: string
                      description: >-
                        Longer description of this specific instance of the
                        problem.
                    source:
                      type: object
                      description: >
                        The source of the current error, exactly one of
                        `pointer`, `parameter` or `line` will be defined.
                      properties:
                        pointer:
                          type: string
                          description: >-
                            Pointer to the path in the payload that caused this
                            error.
                        parameter:
                          type: string
                          description: Query parameter that caused this error.
                        line:
                          type: string
                          description: >-
                            Line number in uploaded multipart file that caused
                            this error. 'N/A' if unknown.
                        resource:
                          type: string
                          description: Pointer to the resource that caused this error.
    '409':
      description: >-
        Conflict. A store with this integration ID already exists for this
        application.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              errors:
                type: array
                description: >-
                  An array of individual problems encountered during the
                  request.
                items:
                  type: object
                  required:
                    - source
                    - title
                  properties:
                    title:
                      type: string
                      description: Short description of the problem.
                    details:
                      type: string
                      description: >-
                        Longer description of this specific instance of the
                        problem.
                    source:
                      type: object
                      description: >
                        The source of the current error, exactly one of
                        `pointer`, `parameter` or `line` will be defined.
                      properties:
                        pointer:
                          type: string
                          description: >-
                            Pointer to the path in the payload that caused this
                            error.
                        parameter:
                          type: string
                          description: Query parameter that caused this error.
                        line:
                          type: string
                          description: >-
                            Line number in uploaded multipart file that caused
                            this error. 'N/A' if unknown.
                        resource:
                          type: string
                          description: Pointer to the resource that caused this error.
              StatusCode:
                type: integer
                description: The error code
