# path: /v1/applications/{applicationId}/customer_activity_reports/no_total
get:
  operationId: getCustomerActivityReportsWithoutTotalCount
  summary: Get Activity Reports for Application Customers
  description: >
    <div class="redoc-warning small">Management API endpoints are <b>not</b>
    meant to be used in real-time integrations that directly serve your end
    users. Rate limit: 3 requests per second.</div>


    Fetch summary reports for all application customers based on a time range.
    Instead of having the total number of results

    in the response, this endpoint only mentions whether there are more results.
  tags:
    - Customer data
  parameters:
    - name: pageSize
      in: query
      required: false
      description: The number of items in the response.
      example: 1000
      schema:
        type: integer
        minimum: 1
        maximum: 1000
        default: 1000
    - name: skip
      in: query
      required: false
      description: The number of items to skip when paging through large result sets.
      example: 100
      schema:
        type: integer
    - name: sort
      in: query
      required: false
      description: >
        The field by which results should be sorted. By default, results are
        sorted in ascending order. To sort them in descending order, prefix the
        field name with `-`.


        **Note:** You may not be able to use all fields for sorting. This is due
        to performance limitations.
      example: name
      schema:
        type: string
    - name: rangeStart
      in: query
      required: true
      description: >
        Only return results from after this timestamp.


        **Note:**

        - This must be an RFC3339 timestamp string.

        - You can include a time component in your string, for example,
        `T23:59:59` to specify the end of the day. The time zone setting
        considered is `UTC`. If you do not include a time component, a default
        time value of `T00:00:00` (midnight) in `UTC` is considered.
      example: '2024-05-29T15:04:05+07:00'
      schema:
        type: string
        format: date-time
    - name: rangeEnd
      in: query
      required: true
      description: >
        Only return results from before this timestamp.


        **Note:**

        - This must be an RFC3339 timestamp string.

        - You can include a time component in your string, for example,
        `T23:59:59` to specify the end of the day. The time zone setting
        considered is `UTC`. If you do not include a time component, a default
        time value of `T00:00:00` (midnight) in `UTC` is considered.
      example: '2024-05-29T15:04:05+07:00'
      schema:
        type: string
        format: date-time
    - name: applicationId
      in: path
      required: true
      description: >-
        The ID of the Application. It is displayed in your Talon.One deployment
        URL.
      example: 42
      schema:
        type: integer
    - name: name
      in: query
      description: Only return reports matching the customer name.
      example: customer1
      required: false
      schema:
        type: string
    - name: integrationId
      in: query
      description: >-
        Filter results performing an exact matching against the profile
        integration identifier.
      example: customer1
      required: false
      schema:
        type: string
    - name: campaignName
      in: query
      description: Only return reports matching the campaign name.
      example: campaign1
      required: false
      schema:
        type: string
    - name: advocateName
      in: query
      description: Only return reports matching the current customer referrer name.
      example: advocate1
      required: false
      schema:
        type: string
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object
            required:
              - hasMore
              - data
            properties:
              hasMore:
                type: boolean
              data:
                type: array
                items:
                  description: >-
                    A summary report of customer activity for a given time
                    range.
                  allOf:
                    - type: object
                      required:
                        - integrationId
                        - created
                      properties:
                        integrationId:
                          type: string
                          format: string
                          example: URNGV8294NV
                          maxLength: 1000
                          description: The integration ID set by your integration layer.
                        created:
                          type: string
                          format: date-time
                          description: The time this entity was created.
                          example: '2020-02-07T08:15:22Z'
                    - type: object
                      required:
                        - name
                        - customerId
                        - integrationId
                        - created
                        - couponRedemptions
                        - couponUseAttempts
                        - couponFailedAttempts
                        - accruedDiscounts
                        - accruedRevenue
                        - totalOrders
                        - totalOrdersNoCoupon
                        - campaignName
                      properties:
                        name:
                          type: string
                          description: The name for this customer profile.
                        customerId:
                          type: integer
                          description: The internal Talon.One ID of the customer.
                        lastActivity:
                          type: string
                          format: date-time
                          description: The last activity of the customer.
                        couponRedemptions:
                          type: integer
                          description: >-
                            Number of coupon redemptions in all customer
                            campaigns.
                        couponUseAttempts:
                          type: integer
                          description: >-
                            Number of coupon use attempts in all customer
                            campaigns.
                        couponFailedAttempts:
                          type: integer
                          description: >-
                            Number of failed coupon use attempts in all customer
                            campaigns.
                        accruedDiscounts:
                          type: number
                          description: >-
                            Number of accrued discounts in all customer
                            campaigns.
                        accruedRevenue:
                          type: number
                          description: Amount of accrued revenue in all customer campaigns.
                        totalOrders:
                          type: integer
                          description: Number of orders in all customer campaigns.
                        totalOrdersNoCoupon:
                          type: integer
                          description: >-
                            Number of orders without coupon used in all customer
                            campaigns.
                        campaignName:
                          type: string
                          description: The name of the campaign this customer belongs to.
