# path: /v1/applications/{applicationId}/campaigns/{campaignId}/coupons_deletion_jobs
post:
  operationId: createCouponsDeletionJob
  summary: Creates a coupon deletion job
  description: >
    <div class="redoc-warning small">Management API endpoints are <b>not</b>
    meant to be used in real-time integrations that directly serve your end
    users. Rate limit: 3 requests per second.</div>


    This endpoint handles creating a job to delete coupons asynchronously.
  tags:
    - Coupons
  parameters:
    - name: applicationId
      in: path
      required: true
      description: >-
        The ID of the Application. It is displayed in your Talon.One deployment
        URL.
      example: 42
      schema:
        type: integer
    - name: campaignId
      in: path
      description: >-
        The ID of the campaign. It is displayed in your Talon.One deployment
        URL.
      example: 18
      required: true
      schema:
        type: integer
  requestBody:
    content:
      application/json:
        schema:
          type: object
          required:
            - filters
          properties:
            filters:
              type: object
              properties:
                createdBefore:
                  description: >-
                    Filter results comparing the parameter value, expected to be
                    an RFC3339 timestamp string, to the coupon creation
                    timestamp. You can use any time zone setting. Talon.One will
                    convert to UTC internally.
                  type: string
                  format: date-time
                createdAfter:
                  description: >-
                    Filter results comparing the parameter value, expected to be
                    an RFC3339 timestamp string, to the coupon creation
                    timestamp. You can use any time zone setting. Talon.One will
                    convert to UTC internally.
                  type: string
                  format: date-time
                startsAfter:
                  description: >-
                    Filter results comparing the parameter value, expected to be
                    an RFC3339 timestamp string, to the coupon creation
                    timestamp. You can use any time zone setting. Talon.One will
                    convert to UTC internally.
                  type: string
                  format: date-time
                startsBefore:
                  description: >-
                    Filter results comparing the parameter value, expected to be
                    an RFC3339 timestamp string, to the coupon creation
                    timestamp. You can use any time zone setting. Talon.One will
                    convert to UTC internally.
                  type: string
                  format: date-time
                valid:
                  enum:
                    - expired
                    - validNow
                    - validFuture
                  description: >
                    - `expired`: Matches coupons in which the expiration date is
                    set and in the past.

                    - `validNow`: Matches coupons in which the start date is
                    null or in the past and the expiration date is null or in
                    the future.

                    - `validFuture`: Matches coupons in which the start date is
                    set and in the future.
                  type: string
                usable:
                  type: boolean
                  description: >
                    - `true`: only coupons where `usageCounter < usageLimit`
                    will be returned.

                    - `false`: only coupons where `usageCounter >= usageLimit`
                    will be returned.

                    - This field cannot be used in conjunction with the `usable`
                    query parameter.
                redeemed:
                  type: boolean
                  description: >
                    - `true`: only coupons where `usageCounter > 0` will be
                    returned.

                    - `false`: only coupons where `usageCounter = 0` will be
                    returned.


                    **Note:** This field cannot be used in conjunction with the
                    `usable` query parameter.
                recipientIntegrationId:
                  description: >
                    Filter results by match with a profile id specified in the
                    coupon's `RecipientIntegrationId` field.
                  type: string
                exactMatch:
                  description: >-
                    Filter results to an exact case-insensitive matching against
                    the coupon code
                  type: boolean
                  default: false
                value:
                  description: Filter results by the coupon code
                  type: string
                batchId:
                  description: Filter results by batches of coupons
                  type: string
                referralId:
                  description: >-
                    Filter the results by matching them with the ID of a
                    referral. This filter shows the coupons created by redeeming
                    a referral code.
                  type: integer
                expiresAfter:
                  description: >-
                    Filter results comparing the parameter value, expected to be
                    an RFC3339 timestamp string, to the coupon creation
                    timestamp. You can use any time zone setting. Talon.One will
                    convert to UTC internally.
                  type: string
                  format: date-time
                expiresBefore:
                  description: >-
                    Filter results comparing the parameter value, expected to be
                    an RFC3339 timestamp string, to the coupon creation
                    timestamp. You can use any time zone setting. Talon.One will
                    convert to UTC internally.
                  type: string
                  format: date-time
    description: body
    required: true
  responses:
    '202':
      description: >-
        The deletion request has been accepted and will be processed
        asynchronously
      content:
        application/json:
          schema:
            allOf:
              - type: object
                required:
                  - id
                properties:
                  id:
                    type: integer
                    description: >-
                      Unique ID for this entity. Not to be confused with the
                      Integration ID, which is set by your integration layer and
                      used in most endpoints.
                    example: 6
              - type: object
