get:
  operationId: getCampaignAnalytics
  summary: Get analytics of campaigns
  description: >-
    <div class="redoc-warning small">Management API endpoints are <b>not</b>
    meant to be used in real-time integrations that directly serve your end
    users. Rate limit: 3 requests per second.</div>


    Retrieve statistical data about the performance of the given campaign.
  tags:
    - Campaigns
  parameters:
    - name: applicationId
      in: path
      required: true
      description: >-
        The ID of the Application. It is displayed in your Talon.One deployment
        URL.
      example: 42
      schema:
        type: integer
    - name: campaignId
      in: path
      description: >-
        The ID of the campaign. It is displayed in your Talon.One deployment
        URL.
      example: 18
      required: true
      schema:
        type: integer
    - name: rangeStart
      in: query
      required: true
      description: >
        Only return results from after this timestamp.


        **Note:**

        - This must be an RFC3339 timestamp string.

        - You can include a time component in your string, for example,
        `T23:59:59` to specify the end of the day. The time zone setting
        considered is `UTC`. If you do not include a time component, a default
        time value of `T00:00:00` (midnight) in `UTC` is considered.
      example: '2024-05-29T15:04:05+07:00'
      schema:
        type: string
        format: date-time
    - name: rangeEnd
      in: query
      required: true
      description: >
        Only return results from before this timestamp.


        **Note:**

        - This must be an RFC3339 timestamp string.

        - You can include a time component in your string, for example,
        `T23:59:59` to specify the end of the day. The time zone setting
        considered is `UTC`. If you do not include a time component, a default
        time value of `T00:00:00` (midnight) in `UTC` is considered.
      example: '2024-05-29T15:04:05+07:00'
      schema:
        type: string
        format: date-time
    - name: granularity
      in: query
      description: The time interval between the results in the returned time-series.
      example: 1 hour
      schema:
        type: string
        enum:
          - 1 hour
          - 1 day
          - 1 week
          - 1 month
          - 1 year
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object
            required:
              - totalResultSize
              - data
            properties:
              totalResultSize:
                type: integer
                example: 1
              data:
                type: array
                items:
                  allOf:
                    - type: object
                      required:
                        - date
                        - campaignRevenue
                        - totalCampaignRevenue
                        - campaignRefund
                        - totalCampaignRefund
                        - campaignDiscountCosts
                        - totalCampaignDiscountCosts
                        - campaignRefundedDiscounts
                        - totalCampaignRefundedDiscounts
                        - campaignFreeItems
                        - totalCampaignFreeItems
                        - referralRedemptions
                        - totalReferralRedemptions
                        - couponRedemptions
                        - totalCouponRedemptions
                        - couponRolledbackRedemptions
                        - totalCouponRolledbackRedemptions
                        - couponsCreated
                        - totalCouponsCreated
                        - referralsCreated
                        - totalReferralsCreated
                        - addedLoyaltyPoints
                        - totalAddedLoyaltyPoints
                        - deductedLoyaltyPoints
                        - totalDeductedLoyaltyPoints
                      properties:
                        date:
                          type: string
                          format: date-time
                          example: '2021-10-12T10:12:42Z'
                        campaignRevenue:
                          type: number
                          description: >-
                            Amount of revenue in this campaign (for coupon or
                            discount sessions).
                          example: 3539.76
                        totalCampaignRevenue:
                          type: number
                          description: >-
                            Amount of revenue in this campaign since it began
                            (for coupon or discount sessions).
                          example: 5784.63
                        campaignRefund:
                          type: number
                          description: >-
                            Amount of refunds in this campaign (for coupon or
                            discount sessions).
                        totalCampaignRefund:
                          type: number
                          description: >-
                            Amount of refunds in this campaign since it began
                            (for coupon or discount sessions).
                        campaignDiscountCosts:
                          type: number
                          description: >-
                            Amount of cost caused by discounts given in the
                            campaign.
                        totalCampaignDiscountCosts:
                          type: number
                          description: >-
                            Amount of cost caused by discounts given in the
                            campaign since it began.
                        campaignRefundedDiscounts:
                          type: number
                          description: >-
                            Amount of discounts rolledback due to refund in the
                            campaign.
                        totalCampaignRefundedDiscounts:
                          type: number
                          description: >-
                            Amount of discounts rolledback due to refund in the
                            campaign since it began.
                        campaignFreeItems:
                          type: integer
                          description: Amount of free items given in the campaign.
                        totalCampaignFreeItems:
                          type: integer
                          description: >-
                            Amount of free items given in the campaign since it
                            began.
                          example: 86
                        couponRedemptions:
                          type: integer
                          description: Number of coupon redemptions in the campaign.
                        totalCouponRedemptions:
                          type: integer
                          description: >-
                            Number of coupon redemptions in the campaign since
                            it began.
                        couponRolledbackRedemptions:
                          type: integer
                          description: >-
                            Number of coupon redemptions that have been rolled
                            back (due to canceling closed session) in the
                            campaign.
                        totalCouponRolledbackRedemptions:
                          type: integer
                          description: >-
                            Number of coupon redemptions that have been rolled
                            back (due to canceling closed session) in the
                            campaign since it began.
                        referralRedemptions:
                          type: integer
                          description: Number of referral redemptions in the campaign.
                        totalReferralRedemptions:
                          type: integer
                          description: >-
                            Number of referral redemptions in the campaign since
                            it began.
                        couponsCreated:
                          type: integer
                          description: >-
                            Number of coupons created in the campaign by the
                            rule engine.
                        totalCouponsCreated:
                          type: integer
                          description: >-
                            Number of coupons created in the campaign by the
                            rule engine since it began.
                        referralsCreated:
                          type: integer
                          description: >-
                            Number of referrals created in the campaign by the
                            rule engine.
                        totalReferralsCreated:
                          type: integer
                          description: >-
                            Number of referrals created in the campaign by the
                            rule engine since it began.
                        addedLoyaltyPoints:
                          type: number
                          description: >-
                            Number of added loyalty points in the campaign in a
                            specific interval.
                          example: 250
                        totalAddedLoyaltyPoints:
                          type: number
                          description: >-
                            Number of added loyalty points in the campaign since
                            it began.
                          example: 340
                        deductedLoyaltyPoints:
                          type: number
                          description: >-
                            Number of deducted loyalty points in the campaign in
                            a specific interval.
                          example: 120
                        totalDeductedLoyaltyPoints:
                          type: number
                          description: >-
                            Number of deducted loyalty points in the campaign
                            since it began.
                          example: 220
