get:
  operationId: getApplicationCustomer
  summary: Get application's customer
  description: >
    <div class="redoc-warning small">Management API endpoints are <b>not</b>
    meant to be used in real-time integrations that directly serve your end
    users. Rate limit: 3 requests per second.</div>


    Retrieve the customers of the specified application.
  tags:
    - Customer data
  parameters:
    - name: applicationId
      in: path
      required: true
      description: >-
        The ID of the Application. It is displayed in your Talon.One deployment
        URL.
      example: 42
      schema:
        type: integer
    - name: customerId
      in: path
      description: >
        The value of the `id` property of a customer profile. Get it with the

        [List Application's
        customers](https://docs.talon.one/management-api#operation/getApplicationCustomers)
        endpoint.
      example: 3778
      required: true
      schema:
        type: integer
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            allOf:
              - type: object
                required:
                  - id
                  - created
                properties:
                  id:
                    type: integer
                    description: The internal ID of this entity.
                    example: 6
                  created:
                    type: string
                    format: date-time
                    description: The time this entity was created.
                    example: '2020-06-10T09:05:27.993483Z'
              - type: object
                required:
                  - integrationId
                  - created
                properties:
                  integrationId:
                    type: string
                    format: string
                    example: URNGV8294NV
                    maxLength: 1000
                    description: The integration ID set by your integration layer.
                  created:
                    type: string
                    format: date-time
                    description: The time this entity was created.
                    example: '2020-02-07T08:15:22Z'
              - allOf:
                  - type: object
                    required:
                      - id
                      - created
                    properties:
                      id:
                        type: integer
                        description: The internal ID of the customer profile.
                        example: 6
                      created:
                        type: string
                        format: date-time
                        description: The time the customer profile was created.
                        example: '2020-06-10T09:05:27.993483Z'
                  - type: object
                    required:
                      - integrationId
                      - created
                    properties:
                      integrationId:
                        type: string
                        format: string
                        example: URNGV8294NV
                        maxLength: 1000
                        description: The integration ID set by your integration layer.
                      created:
                        type: string
                        format: date-time
                        description: The time this entity was created.
                        example: '2020-02-07T08:15:22Z'
                  - type: object
                    properties:
                      attributes:
                        type: object
                        description: Arbitrary properties associated with this item.
                        example:
                          Language: english
                          ShippingCountry: DE
                  - type: object
                    properties:
                      accountId:
                        type: integer
                        title: Profile belongs to Account
                        description: >-
                          The ID of the Talon.One account that owns this
                          profile.
                        example: 31
                      closedSessions:
                        type: integer
                        title: Closed sessions
                        description: >-
                          The total number of closed sessions. Does not include
                          closed sessions that have been cancelled or reopened.
                          See the
                          [docs](https://docs.talon.one/docs/dev/concepts/entities/customer-sessions#customer-session-states).
                        example: 3
                      totalSales:
                        type: number
                        description: >
                          The total amount of money spent by the customer
                          **before** discounts are applied.


                          The total sales amount excludes the following:

                          - Cancelled or reopened sessions.

                          - Returned items.
                        example: 299.99
                        title: Total Sales
                      loyaltyMemberships:
                        type: array
                        description: >
                          **DEPRECATED** A list of loyalty programs joined by
                          the customer.
                        items:
                          type: object
                          required:
                            - loyaltyProgramId
                          properties:
                            joined:
                              type: string
                              format: date-time
                              title: Loyalty program joined at
                              description: >-
                                The moment in which the loyalty program was
                                joined.
                              example: '2012-03-20T14:15:22Z'
                            loyaltyProgramId:
                              type: integer
                              title: Loyalty program ID
                              description: >-
                                The ID of the loyalty program belonging to this
                                entity.
                              example: 323414846
                        title: Loyalty programed joined
                      audienceMemberships:
                        type: array
                        description: The audiences the customer belongs to.
                        items:
                          type: object
                          required:
                            - id
                            - name
                          properties:
                            id:
                              type: integer
                              title: Audience ID
                              description: The ID of the audience belonging to this entity.
                              example: 2
                            name:
                              type: string
                              title: Audience Name
                              description: >-
                                The Name of the audience belonging to this
                                entity.
                              example: Travel audience
                        title: Audience memberships
                      lastActivity:
                        type: string
                        format: date-time
                        title: Last activity
                        description: >
                          Timestamp of the most recent event received from this
                          customer.

                          This field is updated on calls that trigger the Rule
                          Engine and that are

                          not [dry
                          requests](https://docs.talon.one/docs/dev/integration-api/dry-requests/#overlay).


                          For example, [reserving a
                          coupon](https://docs.talon.one/integration-api#operation/createCouponReservation)

                          for a customer doesn't impact this field.
                        example: '2020-02-08T14:15:20Z'
                      sandbox:
                        type: boolean
                        description: >
                          An indicator of whether the customer is part of a
                          sandbox or live Application. See the
                          [docs](https://docs.talon.one/docs/product/applications/overview#application-environments).
                        title: Sandbox
                        example: false
                    required:
                      - accountId
                      - closedSessions
                      - totalSales
                      - lastActivity
                      - attributes
              - type: object
                required:
                  - accountId
                properties:
                  accountId:
                    type: integer
                    description: The ID of the Talon.One account that owns this profile.
                  advocateIntegrationId:
                    type: string
                    maxLength: 1000
                    description: >-
                      The Integration ID of the Customer Profile that referred
                      this Customer in the Application.
