get:
  operationId: getAchievement
  summary: Get achievement
  description: >-
    <div class="redoc-warning small">Management API endpoints are <b>not</b>
    meant to be used in real-time integrations that directly serve your end
    users. Rate limit: 3 requests per second.</div>


    Get the details of a specific achievement.
  tags:
    - Achievements
  parameters:
    - name: applicationId
      in: path
      required: true
      description: >-
        The ID of the Application. It is displayed in your Talon.One deployment
        URL.
      example: 42
      schema:
        type: integer
    - name: campaignId
      in: path
      description: >-
        The ID of the campaign. It is displayed in your Talon.One deployment
        URL.
      example: 18
      required: true
      schema:
        type: integer
    - name: achievementId
      in: path
      description: >-
        The ID of the achievement. You can get this ID with the [List
        achievement](https://docs.talon.one/management-api#tag/Achievements/operation/listAchievements)
        endpoint.
      example: 45
      required: true
      schema:
        type: integer
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            allOf: &ref_2
              - type: object
                required:
                  - id
                  - created
                properties:
                  id:
                    type: integer
                    description: The internal ID of this entity.
                    example: 6
                  created:
                    type: string
                    format: date-time
                    description: The time this entity was created.
                    example: '2020-06-10T09:05:27.993483Z'
              - allOf:
                  - type: object
                    properties: &ref_1
                      name:
                        type: string
                        pattern: ^[a-zA-Z]\w+$
                        example: Order50Discount
                        maxLength: 1000
                        minLength: 1
                        description: >
                          The internal name of the achievement used in API
                          requests.


                          **Note**: The name should start with a letter. This
                          cannot be changed after the achievement has been
                          created.
                      title:
                        type: string
                        description: >-
                          The display name for the achievement in the Campaign
                          Manager.
                        example: 50% off on 50th purchase.
                      description:
                        type: string
                        format: string
                        description: A description of the achievement.
                        example: 50% off for every 50th purchase in a year.
                      target:
                        type: number
                        description: >-
                          The required number of actions or the transactional
                          milestone to complete the achievement.
                        example: 50
                      period:
                        type: string
                        description: >
                          The relative duration after which the achievement ends
                          and resets for a particular customer profile.


                          **Note**: The `period` does not start when the
                          achievement is created.


                          The period is a **positive real number** followed by
                          one letter indicating the time unit.


                          Examples: `30s`, `40m`, `1h`, `5D`, `7W`, `10M`,
                          `15Y`.


                          Available units:


                          - `s`: seconds

                          - `m`: minutes

                          - `h`: hours

                          - `D`: days

                          - `W`: weeks

                          - `M`: months

                          - `Y`: years


                          You can also round certain units down to the beginning
                          of period and up to the end of period.:

                          - `_D` for rounding down days only. Signifies the
                          start of the day.

                          Example: `30D_D`

                          - `_U` for rounding up days, weeks, months and years.
                          Signifies the end of the day, week, month or year.

                          Example: `23W_U`


                          **Note**: You can either use the round down and round
                          up option or set an absolute period.
                        example: 1Y
                      periodEndOverride:
                        deprecated: true
                        type: object
                        required:
                          - hour
                          - minute
                          - second
                        description: >
                          The absolute duration after which the achievement ends
                          and resets for a particular customer profile.


                          **Note**: The duration follows the time zone of the
                          Application this achievement belongs to.
                        properties:
                          month:
                            type: integer
                            minimum: 1
                            maximum: 12
                            description: >
                              The achievement ends and resets in this month.


                              **Note**: Only applicable if the period is set to
                              `Y`.
                            example: 11
                          dayOfMonth:
                            type: integer
                            minimum: 1
                            maximum: 31
                            description: >
                              The achievement ends and resets on this day of the
                              month.


                              **Note**: Only applicable if the period is set to
                              `Y` or `M`.
                            example: 23
                          dayOfWeek:
                            type: integer
                            minimum: 1
                            maximum: 7
                            description: >
                              The achievement ends and resets on this day of the
                              week. `1` represents `Monday` and `7` represents
                              `Sunday`.


                              **Note**: Only applicable if the period is set to
                              `W`.
                          hour:
                            type: integer
                            description: The achievement ends and resets at this hour.
                            example: 23
                          minute:
                            type: integer
                            description: The achievement ends and resets at this minute.
                            example: 59
                          second:
                            type: integer
                            description: The achievement ends and resets at this second.
                            example: 59
                        example:
                          month: 11
                          dayOfMonth: 23
                          hour: 23
                          minute: 59
                          second: 59
                      recurrencePolicy:
                        type: string
                        enum:
                          - no_recurrence
                          - on_expiration
                          - on_completion
                        example: no_recurrence
                        description: >
                          The policy that determines if and how the achievement
                          recurs.

                          - `no_recurrence`: The achievement can be completed
                          only once.

                          - `on_expiration`: The achievement resets after it
                          expires and becomes available again.

                          - `on_completion`: When the customer progress status
                          reaches `completed`, the achievement resets and
                          becomes available again.
                      activationPolicy:
                        type: string
                        enum:
                          - user_action
                          - fixed_schedule
                        example: fixed_schedule
                        description: >
                          The policy that determines how the achievement starts,
                          ends, or resets.

                          - `user_action`: The achievement ends or resets
                          relative to when the customer started the achievement.

                          - `fixed_schedule`: The achievement starts, ends, or
                          resets for all customers following a fixed schedule.
                      fixedStartDate:
                        type: string
                        format: date-time
                        example: 2024-01-15T15:04:05Z07:00
                        description: >
                          The achievement's start date when `activationPolicy`
                          is set to `fixed_schedule`.


                          **Note:** It must be an RFC3339 timestamp string.
                      endDate:
                        type: string
                        format: date-time
                        example: 2024-02-15T15:04:05Z07:00
                        description: >
                          The achievement's end date. If defined, customers
                          cannot participate in the achievement after this date.


                          **Note:** It must be an RFC3339 timestamp string.
                  - type: object
                    required:
                      - name
                      - title
                      - description
                      - target
              - type: object
                required:
                  - campaignId
                  - userId
                properties:
                  campaignId:
                    type: integer
                    description: The ID of the campaign the achievement belongs to.
                    example: 1
                  userId:
                    type: integer
                    description: ID of the user that created this achievement.
                    example: 1234
                  createdBy:
                    type: string
                    description: >
                      Name of the user that created the achievement.


                      **Note**: This is not available if the user has been
                      deleted.
                    example: John Doe
                  hasProgress:
                    type: boolean
                    description: >-
                      Indicates if a customer has made progress in the
                      achievement.
                  status:
                    type: string
                    enum:
                      - inprogress
                      - expired
                      - not_started
                      - completed
                    example: inprogress
                    description: The status of the achievement.
              - type: object
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties: &ref_0
              message:
                type: string
              errors:
                type: array
                description: >-
                  An array of individual problems encountered during the
                  request.
                items:
                  type: object
                  required:
                    - source
                    - title
                  properties:
                    title:
                      type: string
                      description: Short description of the problem.
                    details:
                      type: string
                      description: >-
                        Longer description of this specific instance of the
                        problem.
                    source:
                      type: object
                      description: >
                        The source of the current error, exactly one of
                        `pointer`, `parameter` or `line` will be defined.
                      properties:
                        pointer:
                          type: string
                          description: >-
                            Pointer to the path in the payload that caused this
                            error.
                        parameter:
                          type: string
                          description: Query parameter that caused this error.
                        line:
                          type: string
                          description: >-
                            Line number in uploaded multipart file that caused
                            this error. 'N/A' if unknown.
                        resource:
                          type: string
                          description: Pointer to the resource that caused this error.
              StatusCode:
                type: integer
                description: The error code
    '404':
      description: Not found
      content:
        application/json:
          schema:
            type: object
            properties: *ref_0
put:
  operationId: updateAchievement
  summary: Update achievement
  description: >-
    <div class="redoc-warning small">Management API endpoints are <b>not</b>
    meant to be used in real-time integrations that directly serve your end
    users. Rate limit: 3 requests per second.</div>


    Update the details of a specific achievement.
  tags:
    - Achievements
  parameters:
    - name: applicationId
      in: path
      required: true
      description: >-
        The ID of the Application. It is displayed in your Talon.One deployment
        URL.
      example: 42
      schema:
        type: integer
    - name: campaignId
      in: path
      description: >-
        The ID of the campaign. It is displayed in your Talon.One deployment
        URL.
      example: 18
      required: true
      schema:
        type: integer
    - name: achievementId
      in: path
      description: >-
        The ID of the achievement. You can get this ID with the [List
        achievement](https://docs.talon.one/management-api#tag/Achievements/operation/listAchievements)
        endpoint.
      example: 45
      required: true
      schema:
        type: integer
  requestBody:
    content:
      application/json:
        schema:
          allOf:
            - type: object
              properties: *ref_1
    description: body
    required: true
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            allOf: *ref_2
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            type: object
            properties: *ref_0
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties: *ref_0
    '404':
      description: Not found
      content:
        application/json:
          schema:
            type: object
            properties: *ref_0
delete:
  operationId: deleteAchievement
  summary: Delete achievement
  description: >-
    <div class="redoc-warning small">Management API endpoints are <b>not</b>
    meant to be used in real-time integrations that directly serve your end
    users. Rate limit: 3 requests per second.</div>


    Delete the specified achievement.
  tags:
    - Achievements
  parameters:
    - name: applicationId
      in: path
      required: true
      description: >-
        The ID of the Application. It is displayed in your Talon.One deployment
        URL.
      example: 42
      schema:
        type: integer
    - name: campaignId
      in: path
      description: >-
        The ID of the campaign. It is displayed in your Talon.One deployment
        URL.
      example: 18
      required: true
      schema:
        type: integer
    - name: achievementId
      in: path
      description: >-
        The ID of the achievement. You can get this ID with the [List
        achievement](https://docs.talon.one/management-api#tag/Achievements/operation/listAchievements)
        endpoint.
      example: 45
      required: true
      schema:
        type: integer
  responses:
    '204':
      description: No Content
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties: *ref_0
    '404':
      description: Not found
      content:
        application/json:
          schema:
            type: object
            properties: *ref_0
