get:
  operationId: getCollection
  summary: Get campaign-level collection
  description: >-
    <div class="redoc-warning small">Management API endpoints are <b>not</b>
    meant to be used in real-time integrations that directly serve your end
    users. Rate limit: 3 requests per second.</div>


    Retrieve a given campaign-level collection.
  tags:
    - Collections
  parameters:
    - name: applicationId
      in: path
      required: true
      description: >-
        The ID of the Application. It is displayed in your Talon.One deployment
        URL.
      example: 42
      schema:
        type: integer
    - name: campaignId
      in: path
      description: >-
        The ID of the campaign. It is displayed in your Talon.One deployment
        URL.
      example: 18
      required: true
      schema:
        type: integer
    - name: collectionId
      in: path
      required: true
      description: >-
        The ID of the collection. You can get it with the [List collections in
        Application](#operation/listCollectionsInApplication) endpoint.
      example: 44
      schema:
        type: integer
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            allOf:
              - allOf:
                  - type: object
                    required:
                      - id
                      - created
                    properties:
                      id:
                        type: integer
                        description: The internal ID of this entity.
                        example: 6
                      created:
                        type: string
                        format: date-time
                        description: The time this entity was created.
                        example: '2020-06-10T09:05:27.993483Z'
                  - type: object
                    required:
                      - accountId
                    properties:
                      accountId:
                        type: integer
                        description: The ID of the account that owns this entity.
                        example: 3886
                  - type: object
                    required:
                      - modified
                    properties:
                      modified:
                        type: string
                        format: date-time
                        description: The time this entity was last modified.
                        example: '2021-09-12T10:12:42Z'
                  - allOf:
                      - type: object
                        properties:
                          description:
                            type: string
                            description: >-
                              A short description of the purpose of this
                              collection.
                            example: My collection of SKUs
                          subscribedApplicationsIds:
                            type: array
                            description: >-
                              A list of the IDs of the Applications where this
                              collection is enabled.
                            example:
                              - 1
                              - 2
                              - 3
                            items:
                              type: integer
                      - type: object
                        required:
                          - name
                        properties:
                          name:
                            type: string
                            minLength: 1
                            pattern: ^[^[:cntrl:]\s][^[:cntrl:]]*$
                            description: The name of this collection.
                            example: My collection
                  - type: object
                    required:
                      - createdBy
                    properties:
                      modifiedBy:
                        type: integer
                        description: >-
                          ID of the user who last updated this effect if
                          available.
                        example: 48
                      createdBy:
                        type: integer
                        description: ID of the user who created this effect.
                        example: 134
                      applicationId:
                        type: integer
                        description: The ID of the Application that owns this entity.
                        example: 1
                      campaignId:
                        type: integer
                        description: The ID of the campaign that owns this entity.
                        example: 7
              - type: object
                properties:
                  payload:
                    type: array
                    description: The content of the collection.
                    maxItems: 50
                    example:
                      - KTL-WH-ET-1
                      - KTL-BL-ET-1
                    items:
                      type: string
    '404':
      description: Not found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              errors:
                type: array
                description: >-
                  An array of individual problems encountered during the
                  request.
                items:
                  type: object
                  required:
                    - source
                    - title
                  properties:
                    title:
                      type: string
                      description: Short description of the problem.
                    details:
                      type: string
                      description: >-
                        Longer description of this specific instance of the
                        problem.
                    source:
                      type: object
                      description: >
                        The source of the current error, exactly one of
                        `pointer`, `parameter` or `line` will be defined.
                      properties:
                        pointer:
                          type: string
                          description: >-
                            Pointer to the path in the payload that caused this
                            error.
                        parameter:
                          type: string
                          description: Query parameter that caused this error.
                        line:
                          type: string
                          description: >-
                            Line number in uploaded multipart file that caused
                            this error. 'N/A' if unknown.
                        resource:
                          type: string
                          description: Pointer to the resource that caused this error.
              StatusCode:
                type: integer
                description: The error code
put:
  operationId: updateCollection
  summary: Update campaign-level collection's description
  description: >-
    <div class="redoc-warning small">Management API endpoints are <b>not</b>
    meant to be used in real-time integrations that directly serve your end
    users. Rate limit: 3 requests per second.</div>


    Edit the description of a given campaign-level collection.
  tags:
    - Collections
  parameters:
    - name: applicationId
      in: path
      required: true
      description: >-
        The ID of the Application. It is displayed in your Talon.One deployment
        URL.
      example: 42
      schema:
        type: integer
    - name: campaignId
      in: path
      description: >-
        The ID of the campaign. It is displayed in your Talon.One deployment
        URL.
      example: 18
      required: true
      schema:
        type: integer
    - name: collectionId
      in: path
      required: true
      description: >-
        The ID of the collection. You can get it with the [List collections in
        Application](#operation/listCollectionsInApplication) endpoint.
      example: 44
      schema:
        type: integer
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            description:
              type: string
              description: A short description of the purpose of this collection.
              example: My collection of SKUs
    description: body
    required: true
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            allOf:
              - allOf:
                  - type: object
                    required:
                      - id
                      - created
                    properties:
                      id:
                        type: integer
                        description: The internal ID of this entity.
                        example: 6
                      created:
                        type: string
                        format: date-time
                        description: The time this entity was created.
                        example: '2020-06-10T09:05:27.993483Z'
                  - type: object
                    required:
                      - accountId
                    properties:
                      accountId:
                        type: integer
                        description: The ID of the account that owns this entity.
                        example: 3886
                  - type: object
                    required:
                      - modified
                    properties:
                      modified:
                        type: string
                        format: date-time
                        description: The time this entity was last modified.
                        example: '2021-09-12T10:12:42Z'
                  - allOf:
                      - type: object
                        properties:
                          description:
                            type: string
                            description: >-
                              A short description of the purpose of this
                              collection.
                            example: My collection of SKUs
                          subscribedApplicationsIds:
                            type: array
                            description: >-
                              A list of the IDs of the Applications where this
                              collection is enabled.
                            example:
                              - 1
                              - 2
                              - 3
                            items:
                              type: integer
                      - type: object
                        required:
                          - name
                        properties:
                          name:
                            type: string
                            minLength: 1
                            pattern: ^[^[:cntrl:]\s][^[:cntrl:]]*$
                            description: The name of this collection.
                            example: My collection
                  - type: object
                    required:
                      - createdBy
                    properties:
                      modifiedBy:
                        type: integer
                        description: >-
                          ID of the user who last updated this effect if
                          available.
                        example: 48
                      createdBy:
                        type: integer
                        description: ID of the user who created this effect.
                        example: 134
                      applicationId:
                        type: integer
                        description: The ID of the Application that owns this entity.
                        example: 1
                      campaignId:
                        type: integer
                        description: The ID of the campaign that owns this entity.
                        example: 7
              - type: object
                properties:
                  payload:
                    type: array
                    description: The content of the collection.
                    maxItems: 50
                    example:
                      - KTL-WH-ET-1
                      - KTL-BL-ET-1
                    items:
                      type: string
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              errors:
                type: array
                description: >-
                  An array of individual problems encountered during the
                  request.
                items:
                  type: object
                  required:
                    - source
                    - title
                  properties:
                    title:
                      type: string
                      description: Short description of the problem.
                    details:
                      type: string
                      description: >-
                        Longer description of this specific instance of the
                        problem.
                    source:
                      type: object
                      description: >
                        The source of the current error, exactly one of
                        `pointer`, `parameter` or `line` will be defined.
                      properties:
                        pointer:
                          type: string
                          description: >-
                            Pointer to the path in the payload that caused this
                            error.
                        parameter:
                          type: string
                          description: Query parameter that caused this error.
                        line:
                          type: string
                          description: >-
                            Line number in uploaded multipart file that caused
                            this error. 'N/A' if unknown.
                        resource:
                          type: string
                          description: Pointer to the resource that caused this error.
              StatusCode:
                type: integer
                description: The error code
delete:
  operationId: deleteCollection
  summary: Delete campaign-level collection
  description: >-
    <div class="redoc-warning small">Management API endpoints are <b>not</b>
    meant to be used in real-time integrations that directly serve your end
    users. Rate limit: 3 requests per second.</div>


    Delete a given campaign-level collection.
  tags:
    - Collections
  parameters:
    - name: applicationId
      in: path
      required: true
      description: >-
        The ID of the Application. It is displayed in your Talon.One deployment
        URL.
      example: 42
      schema:
        type: integer
    - name: campaignId
      in: path
      description: >-
        The ID of the campaign. It is displayed in your Talon.One deployment
        URL.
      example: 18
      required: true
      schema:
        type: integer
    - name: collectionId
      in: path
      required: true
      description: >-
        The ID of the collection. You can get it with the [List collections in
        Application](#operation/listCollectionsInApplication) endpoint.
      example: 44
      schema:
        type: integer
  responses:
    '204':
      description: No Content
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              errors:
                type: array
                description: >-
                  An array of individual problems encountered during the
                  request.
                items:
                  type: object
                  required:
                    - source
                    - title
                  properties:
                    title:
                      type: string
                      description: Short description of the problem.
                    details:
                      type: string
                      description: >-
                        Longer description of this specific instance of the
                        problem.
                    source:
                      type: object
                      description: >
                        The source of the current error, exactly one of
                        `pointer`, `parameter` or `line` will be defined.
                      properties:
                        pointer:
                          type: string
                          description: >-
                            Pointer to the path in the payload that caused this
                            error.
                        parameter:
                          type: string
                          description: Query parameter that caused this error.
                        line:
                          type: string
                          description: >-
                            Line number in uploaded multipart file that caused
                            this error. 'N/A' if unknown.
                        resource:
                          type: string
                          description: Pointer to the resource that caused this error.
              StatusCode:
                type: integer
                description: The error code
