get:
  operationId: getApplicationApiHealth
  summary: Get Application health
  description: >
    <div class="redoc-warning small">Management API endpoints are <b>not</b>
    meant to be used in real-time integrations that directly serve your end
    users. Rate limit: 3 requests per second.</div>


    Display the health of the Application and show the last time the Application

    was used.


    You can also find this information in the Campaign Manager. In your
    Application, click **Settings** > **Integration API Keys**.

    See the
    [docs](https://docs.talon.one/docs/dev/tutorials/monitoring-integration-status).
  tags:
    - Applications
  parameters:
    - name: applicationId
      in: path
      required: true
      description: >-
        The ID of the Application. It is displayed in your Talon.One deployment
        URL.
      example: 42
      schema:
        type: integer
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object
            description: Report of health of the API connection of an application.
            required:
              - summary
              - lastUsed
            properties:
              summary:
                type: string
                description: >
                  One-word summary of the health of the API connection of an
                  application. Possible values are:

                  - `OK`: The Application has received only successful API
                  requests in the last 5 minutes.

                  - `WARNING`: The Application received at least one failed
                  request in the last 50 minutes.

                  - `ERROR`: More than 50% of received requests failed.

                  - `CRITICAL`: All received requests failed.

                  - `NONE`: During the last 5 minutes, the Application hasn't
                  recorded any integration API requests.
                enum:
                  - OK
                  - WARNING
                  - ERROR
                  - CRITICAL
                  - NONE
              lastUsed:
                type: string
                format: date-time
                description: time of last request relevant to the API health test.
                example: '2021-09-12T10:12:42Z'
