get:
  operationId: getCustomerProfileAchievementProgress
  summary: List customer achievements
  description: >
    <div class="redoc-warning small">Management API endpoints are <b>not</b>
    meant to be used in real-time integrations that directly serve your end
    users. Rate limit: 3 requests per second.</div>


    For the given customer profile, list all the achievements that match your
    filter criteria.
  tags:
    - Achievements
  parameters:
    - name: applicationId
      in: path
      required: true
      description: >-
        The ID of the Application. It is displayed in your Talon.One deployment
        URL.
      example: 42
      schema:
        type: integer
    - in: path
      required: true
      name: integrationId
      description: >
        The integration identifier for this customer profile. Must be:

        - Unique within the deployment.

        - Stable for the customer. Do not use an ID that the customer can update
        themselves. For example, you can use a database ID.


        Once set, you cannot update this identifier.
      example: customer1
      schema:
        type: string
    - name: pageSize
      in: query
      required: false
      description: The number of items in the response.
      example: 50
      schema:
        type: integer
        minimum: 1
        maximum: 50
        default: 50
    - name: skip
      in: query
      required: false
      description: The number of items to skip when paging through large result sets.
      example: 100
      schema:
        type: integer
    - name: achievementId
      in: query
      description: >-
        The ID of the achievement. You can get this ID with the [List
        achievement](https://docs.talon.one/management-api#tag/Achievements/operation/listAchievements)
        endpoint.
      example: 41
      required: false
      schema:
        type: integer
    - name: title
      in: query
      required: false
      description: Filter results by the `title` of an achievement.
      example: achievement1
      schema:
        type: string
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object
            required:
              - hasMore
              - data
            properties:
              hasMore:
                type: boolean
                example: true
              data:
                type: array
                items:
                  allOf:
                    - type: object
                      description: The current progress of the customer in the achievement.
                      required:
                        - status
                        - progress
                      properties:
                        status:
                          type: string
                          enum:
                            - inprogress
                            - completed
                            - expired
                            - not_started
                          example: completed
                          description: The status of the achievement.
                        progress:
                          type: number
                          example: 10
                          description: >-
                            The current progress of the customer in the
                            achievement.
                        startDate:
                          format: date-time
                          description: >-
                            Timestamp at which the customer started the
                            achievement.
                          type: string
                          example: 2024-01-01T15:04:05Z07:00
                        completionDate:
                          format: date-time
                          description: >-
                            Timestamp at which point the customer completed the
                            achievement.
                          type: string
                          example: 2024-01-15T15:04:05Z07:00
                        endDate:
                          format: date-time
                          description: >-
                            Timestamp at which point the achievement ends and
                            resets for the customer.
                          type: string
                          example: 2024-02-01T15:04:05Z07:00
                    - type: object
                      required:
                        - achievementId
                        - name
                        - title
                        - description
                        - achievementRecurrencePolicy
                        - achievementActivationPolicy
                        - campaignId
                      properties:
                        achievementId:
                          type: integer
                          example: 3
                          description: The internal ID of the achievement.
                        name:
                          type: string
                          pattern: ^[a-zA-Z]\w+$
                          example: FreeCoffee10Orders
                          maxLength: 1000
                          minLength: 1
                          description: >
                            The internal name of the achievement used in API
                            requests.
                        title:
                          type: string
                          description: >-
                            The display name of the achievement in the Campaign
                            Manager.
                          example: 50% off on 50th purchase.
                        description:
                          type: string
                          format: string
                          description: >-
                            The description of the achievement in the Campaign
                            Manager.
                          example: 50% off for every 50th purchase in a year.
                        campaignId:
                          type: integer
                          description: The ID of the campaign the achievement belongs to.
                          example: 3
                        target:
                          type: number
                          example: 10
                          description: >-
                            The required number of actions or the transactional
                            milestone to complete the achievement.
                        achievementRecurrencePolicy:
                          type: string
                          enum:
                            - no_recurrence
                            - on_expiration
                            - on_completion
                          example: no_recurrence
                          description: >
                            The policy that determines if and how the
                            achievement recurs.

                            - `no_recurrence`: The achievement can be completed
                            only once.

                            - `on_expiration`: The achievement resets after it
                            expires and becomes available again.

                            - `on_completion`: When the customer progress status
                            reaches `completed`, the achievement resets and
                            becomes available again.
                        achievementActivationPolicy:
                          type: string
                          enum:
                            - user_action
                            - fixed_schedule
                          example: fixed_schedule
                          description: >
                            The policy that determines how the achievement
                            starts, ends, or resets.

                            - `user_action`: The achievement ends or resets
                            relative to when the customer started the
                            achievement.

                            - `fixed_schedule`: The achievement starts, ends, or
                            resets for all customers following a fixed schedule.
                        achievementFixedStartDate:
                          type: string
                          format: date-time
                          example: 2024-01-15T15:04:05Z07:00
                          description: >
                            The achievement's start date when
                            `achievementActivationPolicy` is equal to
                            `fixed_schedule`.


                            **Note:** It is an RFC3339 timestamp string.
                        achievementEndDate:
                          type: string
                          format: date-time
                          example: 2024-02-15T15:04:05Z07:00
                          description: >
                            The achievement's end date. If defined, customers
                            cannot participate in the achievement after this
                            date.


                            **Note:** It is an RFC3339 timestamp string.
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              errors:
                type: array
                description: >-
                  An array of individual problems encountered during the
                  request.
                items:
                  type: object
                  required:
                    - source
                    - title
                  properties:
                    title:
                      type: string
                      description: Short description of the problem.
                    details:
                      type: string
                      description: >-
                        Longer description of this specific instance of the
                        problem.
                    source:
                      type: object
                      description: >
                        The source of the current error, exactly one of
                        `pointer`, `parameter` or `line` will be defined.
                      properties:
                        pointer:
                          type: string
                          description: >-
                            Pointer to the path in the payload that caused this
                            error.
                        parameter:
                          type: string
                          description: Query parameter that caused this error.
                        line:
                          type: string
                          description: >-
                            Line number in uploaded multipart file that caused
                            this error. 'N/A' if unknown.
                        resource:
                          type: string
                          description: Pointer to the resource that caused this error.
              StatusCode:
                type: integer
                description: The error code
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              errors:
                type: array
                description: >-
                  An array of individual problems encountered during the
                  request.
                items:
                  type: object
                  required:
                    - source
                    - title
                  properties:
                    title:
                      type: string
                      description: Short description of the problem.
                    details:
                      type: string
                      description: >-
                        Longer description of this specific instance of the
                        problem.
                    source:
                      type: object
                      description: >
                        The source of the current error, exactly one of
                        `pointer`, `parameter` or `line` will be defined.
                      properties:
                        pointer:
                          type: string
                          description: >-
                            Pointer to the path in the payload that caused this
                            error.
                        parameter:
                          type: string
                          description: Query parameter that caused this error.
                        line:
                          type: string
                          description: >-
                            Line number in uploaded multipart file that caused
                            this error. 'N/A' if unknown.
                        resource:
                          type: string
                          description: Pointer to the resource that caused this error.
              StatusCode:
                type: integer
                description: The error code
