get:
  operationId: exportReferrals
  summary: Export referrals
  description: >
    <div class="redoc-warning small">Management API endpoints are <b>not</b>
    meant to be used in real-time integrations that directly serve your end
    users. Rate limit: 3 requests per second.</div>


    Download a CSV file containing the referrals that match the given
    parameters.


    **Tip:** If the exported CSV file is too large to view, you can [split it
    into multiple
    files](https://www.makeuseof.com/tag/how-to-split-a-huge-csv-excel-workbook-into-seperate-files/).


    The CSV file contains the following columns:


    - `code`: The referral code.

    - `advocateprofileintegrationid`: The profile ID of the advocate.

    - `startdate`: The start date in RFC3339 of the code redemption period.

    - `expirydate`: The end date in RFC3339 of the code redemption period.

    - `limitval`: The maximum number of redemptions of this code. Defaults to
    `1` when left blank.

    - `attributes`: A json object describing _custom_ referral attribute names
    and their values.
  tags:
    - Referrals
  parameters:
    - name: applicationId
      in: path
      required: true
      description: >-
        The ID of the Application. It is displayed in your Talon.One deployment
        URL.
      example: 42
      schema:
        type: integer
    - name: campaignId
      in: query
      description: Filter results by campaign ID.
      example: 49
      schema:
        type: number
    - name: createdBefore
      in: query
      description: >-
        Filter results comparing the parameter value, expected to be an RFC3339
        timestamp string, to the referral creation timestamp. You can use any
        time zone setting. Talon.One will convert to UTC internally.
      required: false
      example: '2024-05-29T15:04:05+07:00'
      schema:
        type: string
        format: date-time
    - name: createdAfter
      in: query
      description: >-
        Filter results comparing the parameter value, expected to be an RFC3339
        timestamp string, to the referral creation timestamp. You can use any
        time zone setting. Talon.One will convert to UTC internally.
      required: false
      example: '2024-05-29T15:04:05+07:00'
      schema:
        type: string
        format: date-time
    - name: valid
      in: query
      description: >
        - `expired`: Matches referrals in which the expiration date is set and
        in the past.

        - `validNow`: Matches referrals in which start date is null or in the
        past and expiration date is null or in the future.

        - `validFuture`: Matches referrals in which start date is set and in the
        future.
      example: validNow
      required: false
      schema:
        type: string
        enum:
          - expired
          - validNow
          - validFuture
    - name: usable
      in: query
      description: >
        - `true`, only referrals where `usageCounter < usageLimit` will be
        returned.

        - `false`, only referrals where `usageCounter >= usageLimit` will be
        returned.
      example: 'true'
      schema:
        type: string
        enum:
          - 'true'
          - 'false'
    - name: batchId
      in: query
      description: Filter results by batches of referrals
      example: nfinccze
      schema:
        type: string
    - name: dateFormat
      in: query
      description: Determines the format of dates in the export document.
      example: excel
      required: false
      schema:
        type: string
        enum:
          - excel
          - ISO8601
  responses:
    '200':
      description: OK
      content:
        application/csv:
          schema:
            type: string
            format: csv
          examples:
            response:
              value: >
                id,created,campaignid,advocateprofileintegrationid,friendprofileintegrationid,startdate,expirydate,code,importid,attributes,batchid,counter,limitval

                687,2021-09-10
                09:21:06,3882,UGAV4628K,,,,3LFC-4BPC,,"{}",pimcxobg,0,9999
