post:
  operationId: createCouponsForMultipleRecipients
  summary: Create coupons for multiple recipients
  description: >-
    <div class="redoc-warning small">Management API endpoints are <b>not</b>
    meant to be used in real-time integrations that directly serve your end
    users. Rate limit: 3 requests per second.</div>


    Create coupons according to some pattern for up to 1000 recipients.
  tags:
    - Coupons
  parameters:
    - name: silent
      in: query
      description: >
        Possible values: `yes` or `no`.

        - `yes`: Increases the performance of the API call by returning a 204
        response.

        - `no`: Returns a 200 response that contains the updated customer
        profiles.
      example: 'yes'
      required: false
      schema:
        type: string
        default: 'yes'
    - name: applicationId
      in: path
      required: true
      description: >-
        The ID of the Application. It is displayed in your Talon.One deployment
        URL.
      example: 42
      schema:
        type: integer
    - name: campaignId
      in: path
      description: >-
        The ID of the campaign. It is displayed in your Talon.One deployment
        URL.
      example: 18
      required: true
      schema:
        type: integer
  requestBody:
    content:
      application/json:
        schema:
          allOf:
            - type: object
              properties: &ref_0
                usageLimit:
                  type: integer
                  minimum: 0
                  maximum: 999999
                  example: 100
                  description: >
                    The number of times the coupon code can be redeemed. `0`
                    means unlimited redemptions but any campaign usage limits
                    will still apply.
                discountLimit:
                  type: number
                  minimum: 0
                  maximum: 1000000000000000
                  example: 30
                  description: >
                    The total discount value that the code can give. Typically
                    used to represent a gift card value.
                reservationLimit:
                  type: integer
                  minimum: 0
                  maximum: 999999
                  example: 45
                  description: >
                    The number of reservations that can be made with this coupon
                    code.
                startDate:
                  type: string
                  format: date-time
                  example: '2020-01-24T14:15:22Z'
                  description: Timestamp at which point the coupon becomes valid.
                expiryDate:
                  type: string
                  format: date-time
                  example: '2023-08-24T14:15:22Z'
                  description: >-
                    Expiration date of the coupon. Coupon never expires if this
                    is omitted.
            - type: object
              additionalProperties: false
              required:
                - recipientsIntegrationIds
                - usageLimit
              properties:
                attributes:
                  type: object
                  description: Arbitrary properties associated with this item.
                  example:
                    venueId: 12
                recipientsIntegrationIds:
                  title: Receiving customer profiles integration IDs
                  type: array
                  example:
                    - URNGV8294NV
                    - BZGGC2454PA
                  items:
                    type: string
                  description: The integration IDs for recipients.
                  maxItems: 1000
                  minItems: 1
                validCharacters:
                  type: array
                  description: >
                    List of characters used to generate the random parts of a
                    code. By default, the list of

                    characters is equivalent to the `[A-Z, 0-9]` regular
                    expression.
                  example:
                    - A
                    - B
                    - C
                    - D
                    - E
                    - F
                    - G
                    - H
                    - I
                    - J
                    - K
                    - L
                    - M
                    - 'N'
                    - O
                    - P
                    - Q
                    - R
                    - S
                    - T
                    - U
                    - V
                    - W
                    - X
                    - 'Y'
                    - Z
                  items:
                    type: string
                couponPattern:
                  type: string
                  description: >
                    The pattern used to generate coupon codes. The character `#`
                    is a placeholder and is replaced by a random character from
                    the `validCharacters` set.
                  example: SUMMER-#####
                  maxLength: 100
                  minLength: 3
    description: body
    required: true
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object
            required:
              - totalResultSize
              - data
            properties:
              totalResultSize:
                type: integer
                example: 1
              data:
                type: array
                items:
                  allOf:
                    - type: object
                      required:
                        - id
                        - created
                      properties:
                        id:
                          type: integer
                          description: The internal ID of the coupon.
                          example: 6
                        created:
                          type: string
                          format: date-time
                          description: The time the coupon was created.
                          example: '2020-06-10T09:05:27.993483Z'
                    - type: object
                      required:
                        - campaignId
                      properties:
                        campaignId:
                          type: integer
                          title: Campaign ID
                          description: The ID of the campaign that owns this entity.
                          example: 211
                    - type: object
                      properties:
                        value:
                          type: string
                          title: Coupon Code
                          description: The coupon code.
                          minLength: 4
                          example: XMAS-20-2021
                    - type: object
                      properties: *ref_0
                    - type: object
                      properties:
                        limits:
                          type: array
                          description: >
                            Limits configuration for a coupon. These limits will
                            override the limits

                            set from the campaign.


                            **Note:** Only usable when creating a single coupon
                            which is not tied to a specific recipient.

                            Only per-profile limits are allowed to be
                            configured.
                          items:
                            type: object
                            required:
                              - action
                              - limit
                              - entities
                            properties:
                              action:
                                type: string
                                description: >
                                  The limitable action to which this limit
                                  applies. For example:

                                  - `setDiscount`

                                  - `setDiscountEffect`

                                  - `redeemCoupon`

                                  - `createCoupon`
                                example: createCoupon
                              limit:
                                type: number
                                minimum: 0
                                example: 1000
                                description: The value to set for the limit.
                              period:
                                description: The period on which the budget limit recurs.
                                type: string
                                enum:
                                  - daily
                                  - weekly
                                  - monthly
                                  - yearly
                                example: yearly
                              entities:
                                type: array
                                description: The entity that this limit applies to.
                                example:
                                  - Coupon
                                items:
                                  type: string
                                  enum:
                                    - Coupon
                                    - Referral
                                    - Profile
                                    - Identifier
                                    - Store
                                    - Session
                    - type: object
                      required:
                        - value
                        - usageCounter
                        - usageLimit
                      properties:
                        usageCounter:
                          type: integer
                          title: Total coupon redemptions
                          example: 10
                          description: >-
                            The number of times the coupon has been successfully
                            redeemed.
                        discountCounter:
                          type: number
                          title: Discounts Given
                          description: >-
                            The amount of discounts given on rules redeeming
                            this coupon. Only usable if a coupon discount budget
                            was set for this coupon.
                          example: 10
                        discountRemainder:
                          type: number
                          title: Coupon Discount Remainder
                          description: The remaining discount this coupon can give.
                          example: 5
                        reservationCounter:
                          type: number
                          title: Number of reservations
                          description: The number of times this coupon has been reserved.
                          example: 1
                        attributes:
                          type: object
                          title: Attributes of coupon
                          description: Custom attributes associated with this coupon.
                        referralId:
                          type: integer
                          title: Advocate ID
                          description: >-
                            The integration ID of the referring customer (if
                            any) for whom this coupon was created as an effect.
                          example: 326632952
                        recipientIntegrationId:
                          title: Recipient ID
                          example: URNGV8294NV
                          type: string
                          maxLength: 1000
                          description: >-
                            The Integration ID of the customer that is allowed
                            to redeem this coupon.
                        importId:
                          title: Import ID
                          type: integer
                          description: The ID of the Import which created this coupon.
                          example: 4
                        reservation:
                          title: Reservation Type
                          type: boolean
                          example: false
                          description: >
                            Defines the reservation type:

                            - `true`: The coupon can be reserved for multiple
                            customers.

                            - `false`: The coupon can be reserved only for one
                            customer. It is a personal code.
                          default: true
                        batchId:
                          title: Batch ID
                          type: string
                          description: The id of the batch the coupon belongs to.
                          example: 32535-43255
                        isReservationMandatory:
                          title: Is reservation mandatory
                          type: boolean
                          example: false
                          description: >-
                            An indication of whether the code can be redeemed
                            only if it has been reserved first.
                          default: false
                        implicitlyReserved:
                          title: Is coupon implicitly reserved for all customers
                          description: >-
                            An indication of whether the coupon is implicitly
                            reserved for all customers.
                          type: boolean
                          example: false
    '204':
      description: No Content
