get:
  operationId: getCouponsWithoutTotalCount
  summary: List coupons
  description: >
    <div class="redoc-warning small">Management API endpoints are <b>not</b>
    meant to be used in real-time integrations that directly serve your end
    users. Rate limit: 3 requests per second.</div>


    List all the coupons matching the specified criteria.
  tags:
    - Coupons
  parameters:
    - name: pageSize
      in: query
      required: false
      description: The number of items in the response.
      example: 1000
      schema:
        type: integer
        minimum: 1
        maximum: 1000
        default: 1000
    - name: skip
      in: query
      required: false
      description: The number of items to skip when paging through large result sets.
      example: 100
      schema:
        type: integer
    - name: sort
      in: query
      required: false
      description: >
        The field by which results should be sorted. By default, results are
        sorted in ascending order. To sort them in descending order, prefix the
        field name with `-`.


        **Note:** You may not be able to use all fields for sorting. This is due
        to performance limitations.
      example: name
      schema:
        type: string
    - name: applicationId
      in: path
      required: true
      description: >-
        The ID of the Application. It is displayed in your Talon.One deployment
        URL.
      example: 42
      schema:
        type: integer
    - name: campaignId
      in: path
      description: >-
        The ID of the campaign. It is displayed in your Talon.One deployment
        URL.
      example: 18
      required: true
      schema:
        type: integer
    - name: value
      in: query
      description: >-
        Filter results performing case-insensitive matching against the coupon
        code. Both the code and the query are folded to remove all
        non-alpha-numeric characters.
      example: SUMMER10
      required: false
      schema:
        type: string
    - name: createdBefore
      in: query
      description: >-
        Filter results comparing the parameter value, expected to be an RFC3339
        timestamp string, to the coupon creation timestamp. You can use any time
        zone setting. Talon.One will convert to UTC internally.
      required: false
      example: '2024-05-29T15:04:05+07:00'
      schema:
        type: string
        format: date-time
    - name: createdAfter
      in: query
      description: >-
        Filter results comparing the parameter value, expected to be an RFC3339
        timestamp string, to the coupon creation timestamp. You can use any time
        zone setting. Talon.One will convert to UTC internally.
      required: false
      example: '2024-05-29T15:04:05+07:00'
      schema:
        type: string
        format: date-time
    - name: valid
      in: query
      description: >
        Either "expired", "validNow", or "validFuture". The first option matches
        coupons in which the expiration date is set and in the past. The second
        matches coupons in which start date is null or in the past and
        expiration date is null or in the future, the third matches coupons in
        which start date is set and in the future.
      example: validNow
      required: false
      schema:
        type: string
        enum:
          - expired
          - validNow
          - validFuture
    - name: usable
      in: query
      description: >
        Either "true" or "false". If "true", only coupons where `usageCounter <
        usageLimit` will be returned, "false" will return only coupons where
        `usageCounter >= usageLimit`.
      example: 'false'
      schema:
        type: string
        enum:
          - 'true'
          - 'false'
    - name: redeemed
      in: query
      description: >
        - `true`: only coupons where `usageCounter > 0` will be returned.

        - `false`: only coupons where `usageCounter = 0` will be returned.

        - This field cannot be used in conjunction with the `usable` query
        parameter.
      example: 'false'
      schema:
        type: string
        enum:
          - 'true'
          - 'false'
    - name: referralId
      in: query
      description: >-
        Filter the results by matching them with the ID of a referral. This
        filter shows the coupons created by redeeming a referral code.
      example: 47
      required: false
      schema:
        type: integer
    - name: recipientIntegrationId
      in: query
      description: >-
        Filter results by match with a profile ID specified in the coupon's
        RecipientIntegrationId field.
      example: customer1
      required: false
      schema:
        type: string
    - name: batchId
      in: query
      description: Filter results by batches of coupons
      example: nfinccze
      required: false
      schema:
        type: string
    - name: exactMatch
      in: query
      description: >-
        Filter results to an exact case-insensitive matching against the coupon
        code.
      example: false
      required: false
      schema:
        type: boolean
        default: false
    - name: expiresBefore
      in: query
      description: >-
        Filter results comparing the parameter value, expected to be an RFC3339
        timestamp string, to the coupon expiration date timestamp. You can use
        any time zone setting. Talon.One will convert to UTC internally.
      required: false
      example: '2024-05-29T15:04:05+07:00'
      schema:
        type: string
        format: date-time
    - name: expiresAfter
      in: query
      description: >-
        Filter results comparing the parameter value, expected to be an RFC3339
        timestamp string, to the coupon expiration date timestamp. You can use
        any time zone setting. Talon.One will convert to UTC internally.
      required: false
      example: '2024-05-29T15:04:05+07:00'
      schema:
        type: string
        format: date-time
    - name: startsBefore
      in: query
      description: >-
        Filter results comparing the parameter value, expected to be an RFC3339
        timestamp string, to the coupon start date timestamp. You can use any
        time zone setting. Talon.One will convert to UTC internally.
      required: false
      example: '2024-05-29T15:04:05+07:00'
      schema:
        type: string
        format: date-time
    - name: startsAfter
      in: query
      description: >-
        Filter results comparing the parameter value, expected to be an RFC3339
        timestamp string, to the coupon start date timestamp. You can use any
        time zone setting. Talon.One will convert to UTC internally.
      required: false
      example: '2024-05-29T15:04:05+07:00'
      schema:
        type: string
        format: date-time
    - name: valuesOnly
      in: query
      description: >-
        Filter results to only return the coupon codes (`value` column) without
        the associated coupon data.
      example: false
      required: false
      schema:
        type: boolean
        default: false
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object
            required:
              - hasMore
              - data
            properties:
              hasMore:
                type: boolean
                example: true
              data:
                type: array
                items:
                  allOf:
                    - type: object
                      required:
                        - id
                        - created
                      properties:
                        id:
                          type: integer
                          description: The internal ID of the coupon.
                          example: 6
                        created:
                          type: string
                          format: date-time
                          description: The time the coupon was created.
                          example: '2020-06-10T09:05:27.993483Z'
                    - type: object
                      required:
                        - campaignId
                      properties:
                        campaignId:
                          type: integer
                          title: Campaign ID
                          description: The ID of the campaign that owns this entity.
                          example: 211
                    - type: object
                      properties:
                        value:
                          type: string
                          title: Coupon Code
                          description: The coupon code.
                          minLength: 4
                          example: XMAS-20-2021
                    - type: object
                      properties:
                        usageLimit:
                          type: integer
                          minimum: 0
                          maximum: 999999
                          example: 100
                          description: >
                            The number of times the coupon code can be redeemed.
                            `0` means unlimited redemptions but any campaign
                            usage limits will still apply.
                        discountLimit:
                          type: number
                          minimum: 0
                          maximum: 1000000000000000
                          example: 30
                          description: >
                            The total discount value that the code can give.
                            Typically used to represent a gift card value.
                        reservationLimit:
                          type: integer
                          minimum: 0
                          maximum: 999999
                          example: 45
                          description: >
                            The number of reservations that can be made with
                            this coupon code.
                        startDate:
                          type: string
                          format: date-time
                          example: '2020-01-24T14:15:22Z'
                          description: Timestamp at which point the coupon becomes valid.
                        expiryDate:
                          type: string
                          format: date-time
                          example: '2023-08-24T14:15:22Z'
                          description: >-
                            Expiration date of the coupon. Coupon never expires
                            if this is omitted.
                    - type: object
                      properties:
                        limits:
                          type: array
                          description: >
                            Limits configuration for a coupon. These limits will
                            override the limits

                            set from the campaign.


                            **Note:** Only usable when creating a single coupon
                            which is not tied to a specific recipient.

                            Only per-profile limits are allowed to be
                            configured.
                          items:
                            type: object
                            required:
                              - action
                              - limit
                              - entities
                            properties:
                              action:
                                type: string
                                description: >
                                  The limitable action to which this limit
                                  applies. For example:

                                  - `setDiscount`

                                  - `setDiscountEffect`

                                  - `redeemCoupon`

                                  - `createCoupon`
                                example: createCoupon
                              limit:
                                type: number
                                minimum: 0
                                example: 1000
                                description: The value to set for the limit.
                              period:
                                description: The period on which the budget limit recurs.
                                type: string
                                enum:
                                  - daily
                                  - weekly
                                  - monthly
                                  - yearly
                                example: yearly
                              entities:
                                type: array
                                description: The entity that this limit applies to.
                                example:
                                  - Coupon
                                items:
                                  type: string
                                  enum:
                                    - Coupon
                                    - Referral
                                    - Profile
                                    - Identifier
                                    - Store
                                    - Session
                    - type: object
                      required:
                        - value
                        - usageCounter
                        - usageLimit
                      properties:
                        usageCounter:
                          type: integer
                          title: Total coupon redemptions
                          example: 10
                          description: >-
                            The number of times the coupon has been successfully
                            redeemed.
                        discountCounter:
                          type: number
                          title: Discounts Given
                          description: >-
                            The amount of discounts given on rules redeeming
                            this coupon. Only usable if a coupon discount budget
                            was set for this coupon.
                          example: 10
                        discountRemainder:
                          type: number
                          title: Coupon Discount Remainder
                          description: The remaining discount this coupon can give.
                          example: 5
                        reservationCounter:
                          type: number
                          title: Number of reservations
                          description: The number of times this coupon has been reserved.
                          example: 1
                        attributes:
                          type: object
                          title: Attributes of coupon
                          description: Custom attributes associated with this coupon.
                        referralId:
                          type: integer
                          title: Advocate ID
                          description: >-
                            The integration ID of the referring customer (if
                            any) for whom this coupon was created as an effect.
                          example: 326632952
                        recipientIntegrationId:
                          title: Recipient ID
                          example: URNGV8294NV
                          type: string
                          maxLength: 1000
                          description: >-
                            The Integration ID of the customer that is allowed
                            to redeem this coupon.
                        importId:
                          title: Import ID
                          type: integer
                          description: The ID of the Import which created this coupon.
                          example: 4
                        reservation:
                          title: Reservation Type
                          type: boolean
                          example: false
                          description: >
                            Defines the reservation type:

                            - `true`: The coupon can be reserved for multiple
                            customers.

                            - `false`: The coupon can be reserved only for one
                            customer. It is a personal code.
                          default: true
                        batchId:
                          title: Batch ID
                          type: string
                          description: The id of the batch the coupon belongs to.
                          example: 32535-43255
                        isReservationMandatory:
                          title: Is reservation mandatory
                          type: boolean
                          example: false
                          description: >-
                            An indication of whether the code can be redeemed
                            only if it has been reserved first.
                          default: false
                        implicitlyReserved:
                          title: Is coupon implicitly reserved for all customers
                          description: >-
                            An indication of whether the coupon is implicitly
                            reserved for all customers.
                          type: boolean
                          example: false
